services:
  db:
    image: postgres:12
    container_name: school_mgmt_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: school_mgmt
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./seed_db/tables.sql:/docker-entrypoint-initdb.d/01_tables.sql
      - ./seed_db/seed-db.sql:/docker-entrypoint-initdb.d/02_seed.sql

volumes:
  postgres_data:
